### ISSUE TITLE
Epic: Fill the gaps in CommonJS support

### ISSUE THREAD

**Issue by naugtur** [endojs/endo#1055]
MetaMask and Agoric both need to still use parts of the npm ecosystem that are relying on cjs module syntax. 
The goal here is to fill the gaps in support for cjs and interoperability with esm (to the extent deemed reasonable)

Tasks:
- [x] https://github.com/endojs/endo/issues/906
- [x] https://github.com/endojs/endo/issues/744
- [x] wontfix for now: https://github.com/endojs/endo/issues/927
- [x] https://github.com/endojs/endo/issues/885
- [x] https://github.com/endojs/endo-e2e-tests/issues/3
- [x] https://github.com/endojs/endo/issues/1056
- [x] https://github.com/endojs/endo/issues/1116
- [x] https://github.com/endojs/endo/pull/1134
- [x] https://github.com/endojs/endo/pull/1155
- [x] #1189
- [x] Exports type handling:
 - https://github.com/endojs/endo/issues/1143
 - #1230 
 - #1231

Merging 1230 or 1231 would be the last item to complete for closing this

End to end tests for cjs support and compatibility matrix here: https://github.com/endojs/endo-e2e-tests

**Comment by naugtur** [comment]
CommonJS support Epic closing party :tada: :partying_face:
