### ISSUE TITLE
SES lockdown Hermes compat tracking issue

### ISSUE THREAD

**Issue by leotm** [endojs/endo#1891]
Briefly demo'd https://github.com/MetaMask/metamask-mobile/pull/8009, a minimally transformed ses@0.18.8 wip that runs on Hermes (latest React Native default JS engine)

here's the omnibus of issues/mods below, while figuring which parts we definitely need (vs can skip/remove in a codemod) cc @erights would appreciate any thoughts

#### Bundling (Metro, release)
- [x] `error: async functions are unsupported`
  - [x] <s>`loadWithoutErrorAnnotation`</s>
  - [x] <s>`memoizedLoadWithErrorAnnotation`</s>
  - [x] `load`
  - [x] `drainQueue` (ses@1.5.0)
  - [x] `asyncTrampoline` (ses@master)
  - fixed in Hermes SES shim variant
    - https://github.com/endojs/endo/commit/d04d591ffd1b0da47d08e49ae2e295b3c5634ae1 https://github.com/leotm/RN07117SES/commit/ebc6ed6d22c44f6b66a49f94917f6c643a3d5c9d
- [x] `error: async generators are unsupported`
  - `async function* AsyncGeneratorFunctionInstance() {}`
  - fixed in Hermes SES shim variant
    - https://github.com/endojs/endo/commit/0421ca7eaf4c69c2343637f495c5e5738230cb8f https://github.com/leotm/RN07117SES/commit/8a64849a8bdba01369015bfe18d0d4a96b833e80

+ [x] SES shim variant for Hermes compiler
  - https://github.com/endojs/endo/pull/2334

#### Runtime
- [x] `// assertDirectEvalAvailable(); // SES TypeError`
  - https://github.com/facebook/hermes/issues/957
    - https://github.com/facebook/hermes/pull/1515
  - _https://github.com/facebook/hermes/issues/1056_
    - https://github.com/facebook/hermes/pull/1571
  - [x] DRAFT https://github.com/endojs/endo/compare/master...ses-hermes-p2
  - [x] https://github.com/endojs/endo/pull/2723
- [x] `addIntrinsics(tameRegExpConstructor(regExpTaming)); // SES TypeError`</s>
  - [x] https://github.com/endojs/endo/pull/2108
- [x] `addIntrinsics(tameSymbolConstructor()); // Metro exception, RN polyfill error guard Fatal Error`</s>
  - [x] https://github.com/endojs/endo/pull/2206
- [x] `addIntrinsics(getAnonymousIntrinsics()); // SES TypeError`
  - reappeared since updating SES
  - [x] https://github.com/endojs/endo/pull/2220
  - [x] https://github.com/endojs/endo/pull/2221
  - [x] fixed in Hermes-specific SES shim variant
- [x] `completePrototypes(); // SES TypeError`
  - [x] https://github.com/endojs/endo/pull/2563
  - [x] https://github.com/endojs/endo/issues/2598
  - [x] https://github.com/endojs/endo/pull/2624
- [x] `whitelistIntrinsics(intrinsics, markVirtualizedNativeFunction); // SES TypeError`
  - nb: now renamed to `removeUnpermittedIntrinsics`
  - [x] https://github.com/endojs/endo/pull/2655
  - [x] https://github.com/facebook/hermes/issues/1582
  - [x] https://github.com/facebook/hermes/commit/bb90b33ac0bc22cdd35eae593de96faa6376437a

#### Non blocking
- https://github.com/endojs/endo/issues/2761

Tested across [bundled Hermes](https://reactnative.dev/architecture/bundled-hermes) for RN
- _0.12.0 ([old](https://github.com/facebook/hermes/releases/tag/v0.12.0) standalone [playground](https://hermesengine.dev/playground/) compiler & vm, esvu fails to fetch Hermes to plug into eshost)_
- 0.71.15 (metamask-mobile): [built from source](https://reactnative.dev/contributing/how-to-build-from-source#update-your-project-to-build-from-source)
  - from: https://github.com/MetaMask/hermes (our fork)
- 0.71.17: [hermes-2023-03-07-RNv0.71.4-xxx: Increase default max stack size (#923)](https://github.com/facebook/hermes/releases/tag/hermes-2023-03-07-RNv0.71.4-ee25883ea34374f687883a641c8101ac0d292fc6)
  - from: https://github.com/facebook/hermes/tree/rn/0.71-stable
  - uses: https://github.com/facebook/flipper/releases/tag/v0.125.0
  - debugger statements pause exec, works once after Metro w Hermes Debugger then broken on Hot Reload
- 0.72.12 (metamask-mobile@next): [hermes-2023-08-07-RNv0.72.4-xxx: Avoid repeated branches while iterating StringView](https://github.com/facebook/hermes/releases/tag/hermes-2023-08-07-RNv0.72.4-813b2def12bc9df02654b3e3653ae4a68d0572e0) no longer build from source
  - from: https://github.com/facebook/hermes/tree/rn/0.72-stable
  - uses: https://github.com/facebook/flipper/releases/tag/v0.182.0
  - debugger statements pause exec, but Hermes Debugger broken
- 0.73.6 (JDK 17): [hermes-2024-02-20-RNv0.73.5-xxx: Mitigate WeakMap cycle leak](https://github.com/facebook/hermes/releases/tag/hermes-2024-02-20-RNv0.73.5-18f99ace4213052c5e7cdbcd39ee9766cd5df7e4)
  - from: https://github.com/facebook/hermes/tree/rn/0.73-stable
  - uses: https://github.com/facebook/flipper/releases/tag/v0.201.0
  - debugger statements pause exec, but Hermes Debugger broken and [deprecated](https://github.com/react-native-community/discussions-and-proposals/pull/641), [new debugger](https://reactnative.dev/docs/0.73/debugging?js-debugger=new-debugger) same
    - https://github.com/react-native-community/discussions-and-proposals/discussions/733#discussioncomment-7598402
    - https://github.com/react-native-community/discussions-and-proposals/discussions/733#discussioncomment-7598428
- 0.74.0-rc.3: [hermes-2024-02-20-RNv0.74.0-xxx: Save exported state across RuntimeAgent instances](https://github.com/facebook/hermes/releases/tag/hermes-2024-02-20-RNv0.74.0-999cfd9979b5f57b1269119679ab8cdf60897de9)
- [Nightly](https://github.com/reactwg/react-native-releases/discussions/49)?: [hermes-2024-03-26-RNvmain-xxx: breakAtPossibleNextInstructions should use const InterpreterState](https://github.com/facebook/hermes/releases/tag/hermes-2024-03-26-RNvmain-86d391d00be80aeccc8b29f62a254ecf6bc8a9ae)
  - from: https://github.com/facebook/hermes/commits/main
- [RNTester](https://github.com/facebook/react-native/tree/main/packages/rn-tester)/RNTestProject?
  - https://github.com/reactwg/react-native-releases/blob/main/docs/guide-release-testing.md

_Nb: latest minor version tags above, side-by-side with Hermes tarballs downloaded during build_

---

## <s>async functions</s>

```console
# ...

metamask-mobile/android/app/build/ASSETS/createBundleProdDebugJsAndAssets/index.android.bundle: error: async functions are unsupported
      const loadWithoutErrorAnnotation = async (compartmentPrivateFields, moduleAliases, compartment, moduleSpecifier, pendingJobs, moduleLoads, errors) => {

metamask-mobile/android/app/build/ASSETS/createBundleProdDebugJsAndAssets/index.android.bundle: error: async functions are unsupported
      const memoizedLoadWithErrorAnnotation = async (compartmentPrivateFields, moduleAliases, compartment, moduleSpecifier, pendingJobs, moduleLoads, errors) => {

metamask-mobile/android/app/build/ASSETS/createBundleProdDebugJsAndAssets/index.android.bundle: error: async functions are unsupported
      const load = async (compartmentPrivateFields, moduleAliases, compartment, moduleSpecifier) => {

mobile/android/app/build/ASSETS/createBundleProdDebugJsAndAssets/index.android.bundle:1233 error: async generators are unsupported
        async function* AsyncGeneratorFunctionInstance() {}

# ...
```

Nb: `async function* a() {};` alone won't emit an error
but using/referencing it and beyond `const b = a;` will

encountered bundling the app with Metro (considering [Re.Pack](https://github.com/callstack/repack))

```sh
# via RN CLI
yarn watch:clean
yarn start:android # react-native run-android --variant=prodDebug
```

```sh
# or via Gradle Wrapper
./gradlew clean # after changes to SES
./gradlew :app:createBundleProdDebugJsAndAssets # bundle only
./gradlew :app:installProdDebug -PreactNativeArchitectures=arm64-v8a # bundle then build for M2
```

Since Hermes `async` and `await` support is [In Progress](https://hermesengine.dev/docs/language-features/#in-progress) (let alone [async generators](https://github.com/facebook/hermes/blob/main/test/IRGen/es6/async-generators.js))

so Hermes doesn't support async arrow functions directly

but we're getting indirect support later via [@babel/preset-env](https://babeljs.io/docs/babel-preset-env)
- includes [@babel/plugin-transform-async-to-generator](https://babeljs.io/docs/babel-plugin-transform-async-to-generator) in ES2017
which lowers them to generator fns or plain fns using [regenerator](https://github.com/facebook/regenerator) (relies on regenerator-runtime)
  - we require https://github.com/facebook/regenerator/commit/903a50726da73d0ffd5b57a7617bbcc2fd4bbc99 for SES
  - i.e. [regenerator-runtime@0.13.8](https://github.com/facebook/regenerator/releases/tag/regenerator-runtime%400.13.8)+
- includes [@babel/plugin-transform-arrow-functions](https://babeljs.io/docs/babel-plugin-transform-arrow-functions)
- includes [@babel/plugin-transform-async-generator-functions](https://babeljs.io/docs/babel-plugin-transform-async-generator-functions) in ES2018
- includes [@babel/plugin-async-generator-functions](https://babeljs.io/docs/babel-plugin-transform-async-generator-functions) in ES2018 (unused)

```console
# regenerator-runtime
metamask@7.15.0 /Users/leo/Documents/GitHub/metamask-mobile
├─┬ @babel/runtime@7.23.2
│ └── regenerator-runtime@0.14.0
# ...
```

```console
# (old name: babel-plugin-transform-async-to-generator)
metamask@7.15.0 /Users/leo/Documents/GitHub/metamask-mobile
├─┬ @babel/preset-env@7.23.2
│ └── @babel/plugin-transform-async-to-generator@7.22.5
└─┬ metro-react-native-babel-preset@0.73.10
  └── @babel/plugin-transform-async-to-generator@7.22.5 deduped
```

```console
# @babel/plugin-transform-arrow-functions
metamask@7.15.0 /Users/leo/Documents/GitHub/metamask-mobile
├─┬ @babel/preset-env@7.23.2
│ └── @babel/plugin-transform-arrow-functions@7.22.5
├─┬ fbjs-scripts@3.0.1
│ └─┬ babel-preset-fbjs@3.4.0
│   └── @babel/plugin-transform-arrow-functions@7.22.5 deduped
├─┬ metro-react-native-babel-preset@0.73.10
│ └── @babel/plugin-transform-arrow-functions@7.22.5 deduped
└─┬ react-native-reanimated@3.1.0
  └── @babel/plugin-transform-arrow-functions@7.22.5 deduped
```

```console
# @babel/plugin-transform-async-generator-functions
└─┬ @babel/preset-env@7.24.4
  └── @babel/plugin-transform-async-generator-functions@7.24.3
```

```console
# @babel/plugin-async-generator-functions
metamask@7.15.0 /Users/leo/Documents/GitHub/metamask-mobile
└── (empty)
```

_nb: metro-react-native-babel-preset@0.77.0 includes [these](https://github.com/facebook/metro/blob/v0.77.0/packages/metro-react-native-babel-preset/package.json#L21-L58) 37 babel plugins_

If so, re-write to [Promises](https://github.com/MetaMask/metamask-mobile/pull/8161/commits), otherwise [skip parts](https://github.com/MetaMask/metamask-mobile/pull/8161/commits) or remove and refactor, or is there a better solution?

<s>TODO: check refactor from async arrow fns to async fns; check latest bundled Hermes versions of RN</s>

No longer an issue on bundled Hermes for RN 0.71.17+ (i.e. not a custom build from source)

## assertDirectEvalAvailable

<img width="469" alt="SES cannot initialize unless 'eval' is the" src="https://github.com/endojs/endo/assets/1881059/f76979a5-ba01-46ab-affe-ba4e12b17622">

Since `eval` is [Excluded From Support](https://hermesengine.dev/docs/language-features/#excluded-from-support)

- https://github.com/facebook/hermes/issues/957

## <s>tameRegExpConstructor</s>

<img width="346" alt="no RegExpSymbol species descriptor" src="https://github.com/endojs/endo/assets/1881059/f59a2bbe-6792-4c52-84fa-11b8e4f81e3d">

`no RegExp[Symbol.species] descriptor`, `no stack`

ses.cjs#4472: `TypeError('no RegExp[Symbol.species] descriptor');`

<img width="795" alt="Screenshot 2023-11-29 at 11 05 28 am" src="https://github.com/endojs/endo/assets/1881059/c4e516e7-5a8f-4b90-b094-16b58e5efa0d">

```ts
// node_modules/typescript/lib/lib.es2015.symbol.wellknown.d.ts
// ...
/// <reference lib="es2015.symbol" />

interface SymbolConstructor {
// ...
    /**
     * A function valued property that is the constructor function that is used to create
     * derived objects.
     */
    readonly species: unique symbol;
// ...
}
```

This is because it is [Excluded From Support](https://hermesengine.dev/docs/language-features/#excluded-from-support) on Hermes

> `Symbol.species` and its interactions with JS library functions

For a good reason it seems, noting both warnings

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/species

<img width="815" alt="Screenshot 2024-02-28 at 6 51 52 pm" src="https://github.com/endojs/endo/assets/1881059/c729f3db-472e-4c2c-861b-4c1eae690aa5">

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/@@species

<img width="785" alt="Screenshot 2024-03-04 at 11 49 57 am" src="https://github.com/endojs/endo/assets/1881059/9f91f739-6e9c-4f44-b6de-cfae4cdad2b2">

So we likely want this part skipped or tameRegExpConstructor option to skip (plus remaining changes, then upstream)

```js
    if( !speciesDesc) {
      throw TypeError('no RegExp[Symbol.species] descriptor'); // Thrown on Hermes since excluded from support
     }
```

fixed in
- https://github.com/endojs/endo/pull/2108

## tameSymbolConstructor

<img width="258" alt="property is not configurable" src="https://github.com/endojs/endo/assets/1881059/b9ac8c2d-ddd6-4bb8-ab26-3b0013f3492f">

<img width="459" alt="Screenshot 2024-03-04 at 2 23 27 pm" src="https://github.com/endojs/endo/assets/1881059/4b34b932-a6bf-4d4f-bd8b-21805736dd1b">

`property is not configurable`, `no stack` / `at [object CallSite]`

ses.cjs#9481: `defineProperties(SharedSymbol, descs);`

<img width="1344" alt="Screenshot 2023-12-05 at 1 41 49 pm" src="https://github.com/endojs/endo/assets/1881059/2519c891-e03c-4b44-82d4-6c34bdf1275b">

<img width="1000" alt="Screenshot 2023-12-05 at 3 41 43 pm" src="https://github.com/endojs/endo/assets/1881059/c5d87168-ba6f-40db-89cc-917f76c6a13d">

**We can fix this simply by omitting `configurable: true` on Hermes**

```js
  const descs = fromEntries(
    arrayMap(originalDescsEntries, ([name, desc]) => [
      name,
      { ...desc }, // configurable: true, omitted
    ]),
  );
```

in order to tame the Symbol constructor (used on constructed compartments),
we attempt to _temporarily_ make all props `configurable: true`
so that we can whitelist (remove non-standard) props, then harden them (back to non-configurable)

Hermes has 15 `Symbol` props on all versions (contrasted to e.g. Node with 18)

on [metamask-mobile](https://github.com/MetaMask/metamask-mobile) (Android)
when we observe `Object.getOwnPropertyDescriptor(originalDescsEntries, name)?.configurable`
we get 15 non-true props: 1 `false` prop (`length`), 14 `undefined`

nb: on Hermes v0.12.0 built from scratch

```console
➜  bin ./hermes --version
LLVM (http://llvm.org/):
  LLVH version 8.0.0svn
  Optimized build

Hermes JavaScript compiler and Virtual Machine.
  Hermes release version: 0.12.0
  HBC bytecode version: 96

  Features:
    Debugger
    Zip file input
➜  bin ./hermes
>> Object.getOwnPropertyDescriptors(Symbol)
{ length: { value: 0, writable: false, enumerable: false, configurable: true }, name: { value: "Symbol", writable: false, enumerable: false, configurable: true }, prototype: { value: Symbol { [constructor]: [Function Symbol], [description]: [accessor], [toString]: [Function toString], [valueOf]: [Function valueOf], [Symbol(Symbol.toStringTag)]: "Symbol", [Symbol(Symbol.toPrimitive)]: [Function [Symbol.toPrimitive]] }, writable: false, enumerable: false, configurable: false }, for: { value: [Function for], writable: true, enumerable: false, configurable: true }, keyFor: { value: [Function keyFor], writable: true, enumerable: false, configurable: true }, hasInstance: { value: Symbol(Symbol.hasInstance), writable: false, enumerable: false, configurable: false }, iterator: { value: Symbol(Symbol.iterator), writable: false, enumerable: false, configurable: false }, isConcatSpreadable: { value: Symbol(Symbol.isConcatSpreadable), writable: false, enumerable: false, configurable: false }, toPrimitive: { value: Symbol(Symbol.toPrimitive), writable: false, enumerable: false, configurable: false }, toStringTag: { value: Symbol(Symbol.toStringTag), writable: false, enumerable: false, configurable: false }, match: { value: Symbol(Symbol.match), writable: false, enumerable: false, configurable: false }, matchAll: { value: Symbol(Symbol.matchAll), writable: false, enumerable: false, configurable: false }, search: { value: Symbol(Symbol.search), writable: false, enumerable: false, configurable: false }, replace: { value: Symbol(Symbol.replace), writable: false, enumerable: false, configurable: false }, split: { value: Symbol(Symbol.split), writable: false, enumerable: false, configurable: false } }
```

(i built/ran Hermes from [scratch](https://hermesengine.dev/docs/building-and-running/) to observe above, since Hermes via [eshost-cli](https://github.com/bterlson/eshost-cli) on m2 is unsupported via [jsvu(mac64arm)](https://github.com/GoogleChromeLabs/jsvu?tab=readme-ov-file#supported-engines-per-os) and doesn't fetch via [esvu(darwin-arm64)](https://github.com/devsnek/esvu?tab=readme-ov-file#usage) and built Hermes via eshost complains `hermes: Unknown command line argument '-fenable-tdz'` and Hermes [playground](https://hermesengine.dev/playground/) only prints `[object Object]` - but thx for demo'ing @gibson042, jealous how it worked so eloquently on your machine :p)

nb: some Hermes [Language Features](https://hermesengine.dev/docs/language-features)
- excludes: `Symbol.species` and its interactions with JS library functions
- excludes: `Symbol.unscopables` (Hermes does not support `with`)
- **in progress: `Symbol.prototype.description` (it's not fully spec-conformant yet. `Symbol().description` should be `undefined` but it's currently `''`)**
- supports: Iteration (with `[Symbol.iterator]`)
- **supports: Symbols (including most well-known Symbols)**

nb: our `tameSymbolConstructor` fn

```js
// https://github.com/endojs/endo/blob/master/packages/ses/src/tame-symbol-constructor.js
/**
 * This taming provides a tamed alternative to the original `Symbol` constructor
 * that starts off identical, except that all its properties are "temporarily"
 * configurable. The original `Symbol` constructor remains unmodified on
 * the start compartment's global. The tamed alternative is used as the shared
 * `Symbol` constructor on constructed compartments.
 *
 * Starting these properties as configurable assumes two succeeding phases of
 * processing: A whitelisting phase, that
 * removes all properties not on the whitelist (which requires them to be
 * configurable) and a global hardening step that freezes all primordials,
 * returning these properties to their expected non-configurable status.
 *
 * The ses shim is constructed to eventually enable vetted shims to run between
 * repair and global hardening. However, such vetted shims would normally
 * run in the start compartment, which continues to use the original unmodified
 * `Symbol`, so they should not normally be affected by the temporary
 * configurability of these properties.
 *
 * Note that the spec refers to the global `Symbol` function as the
 * ["Symbol Constructor"](https://tc39.es/ecma262/multipage/fundamental-objects.html#sec-symbol-constructor)
 * even though it has a call behavior (can be called as a function) and does not
 * not have a construct behavior (cannot be called with `new`). Accordingly,
 * to tame it, we must replace it with a function without a construct
 * behavior.
 */
```

nb: a `SymbolTaming` lockdown [option](https://github.com/endojs/endo/blob/master/packages/ses/docs/lockdown.md#lockdown-options) doesn't exist yet (same with FunctionTaming on  `tameFunctionConstructors`)

solutions
- tolerate this in ses shim (codemod, or upstream: [`packages/ses/src/tame-symbol-constructor.js`](https://github.com/endojs/endo/blob/master/packages/ses/src/tame-symbol-constructor.js))
- add a lockdown option (upstream: [`packages/ses/src/lockdown.js#L276`](https://github.com/endojs/endo/blob/master/packages/ses/src/lockdown.js#L276))
  - default: `safe` (current implementation)
  - option: `unsafe` (skip taming, none at all)

extra
- instead of throwing a RN polyfill error-guard Fatal Error in Metro on Hermes, throw a similar SES TypeError before instead? unless tolerated
- update `The ses shim is constructed to _eventually_ enable vetted shims...` 10mo ago now we have vetted shims
  - and remaining codebase refs

security considerations pending further thought

## getAnonymousIntrinsics

⚠️ Babel is likely transforming SES, check the config to ensure the shim is ignored ⚠️

<img width="472" alt="Conflicting definitions of InertAsyncFunction" src="https://github.com/endojs/endo/assets/1881059/b97dc165-df06-4b44-bb7b-380ccffaa4d9">

`Conflicting definitions of %InertAsyncFunction%`, `no stack`

ses.cjs#3688: ```TypeError( `Conflicting definitions of ${name}`);```

<img width="1344" alt="Screenshot 2023-12-05 at 3 14 18 pm" src="https://github.com/endojs/endo/assets/1881059/f11cf8aa-d819-4ac7-b2dd-a8915fa58671">

Not present in
- hermes-engine-cli@0.12.0
- react-native@0.71.17
  - `debugger` statements working in _Flipper > Hermes Debugger (RN)_

Present in
- react-native@0.72.15(metamask-mobile)
  - `debugger` statements broken in _Flipper > Hermes Debugger (RN)_

commenting

```js
throw new TypeError(`Conflicting definitions of ${name}`);
```

results in SES continuing to lockdown
resulting in a fully functional React Native app
but at what security cost

```console
%InertFunction% // no conflicting definitions
%InertAsyncFunction% // ❌ conflicting definitions
%InertGeneratorFunction% // no conflicting definitions
```

## completePrototypes

<img width="471" alt="lockdown prototype property not whitelisted" src="https://github.com/endojs/endo/assets/1881059/f20e91e5-69d5-4f06-abeb-991f50a2cbc0">

`lockdown.prototype property not whitelisted`, `no stack`

ses.cjs#3730: ```TypeError( `${name}.prototype property not whitelisted`)```

to repro, uncomment

https://github.com/endojs/endo/blob/cdd2dad04a7b280c5750e74e5dd13c653148da84/packages/ses/scripts/hermes.sh#L38

## whitelistIntrinsics

<img width="468" alt="Unexpected intrinsic intrinsics  isFinite _proto_" src="https://github.com/endojs/endo/assets/1881059/c241bafe-9a88-44e0-bf5a-3b7886a9e7ef">

`Unexpected intrinsic intrinsics.isFinite.__proto__ at %FunctionPrototype%`, `no stack`

ses.cjs#3953: ```TypeError( `Unexpected intrinsic ${path}.__proto__ at ${protoName}`)```

<img width="1344" alt="Screenshot 2023-12-05 at 2 51 49 pm" src="https://github.com/endojs/endo/assets/1881059/813a9ed9-3a65-4f65-971d-1e096a7bb488">

`isFinite` appears to be the first of many intrinsics

No more SES TypeErrors thrown after whitelisting intrinsics

## hardenIntrinsics

No errors visible, but the React Native app hangs

`__hardenTaming__: 'unsafe'` (default safe) fixes the issue, but is not a viable solution

https://github.com/endojs/endo/blob/master/packages/ses/docs/lockdown.md#__hardentaming__-options

The Hermes VM throws

```console
Error running main: (TypeError#1)
TypeError#1: Failed to load module "./index.js" in package "file:///Users/leo/Documents/GitHub/endo/packages/ses/" (1 underlying failures: Error transforming "mjs" source in "file:///Users/leo/Documents/GitHub/endo/packages/ses/index.js": Cannot assign to read only property 'toString' of function 'function (path) {
    if (validator.call(path)) {
      return fn.apply(this, arguments);
    }
  }'

  at throwAggregateError (packages/ses/src/module-load.js:546:11)
  at load (packages/ses/src/module-load.js:594:3)
  at async makeBundle (packages/compartment-mapper/src/bundle.js:292:3)
  at async writeBundle (packages/ses/scripts/bundle.js:50:18)
  at async main (packages/ses/scripts/bundle.js:107:3)
```

**Comment by kriskowal** [comment]
My understanding of this issue is that we’re tracking integration problems with Hermes and some of these may motivate recommendations to change the SES shim to broaden its portability. (I’m driving similar work with XS.) You also are getting by with some transformations and manual edits of the SES shim that might upstream.

@leotm Do you plan to propose changes?

One of the things I am thinking of doing for XS is elaborate the `"exports"` in `package.json` to use a custom variant of SES for that platform. That amounts to including only certain layers, and having some XS-specific layers. I imagine something similar will be in order for Hermes.

```json
{
  "exports": {
    "hermes": {},
    "xsnap": {},
    "default": {},
  }
}
```

**Comment by leotm** [comment]
> My understanding of this issue is that we’re tracking integration problems with Hermes and some of these may motivate recommendations to change the SES shim to broaden its portability. (I’m driving similar work with XS.) You also are getting by with some transformations and manual edits of the SES shim that might upstream.
> 
> @leotm Do you plan to propose changes?
> 
> One of the things I am thinking of doing for XS is elaborate the `"exports"` in `package.json` to use a custom variant of SES for that platform. That amounts to including only certain layers, and having some XS

Exactly ^ renamed to tracking issue, was initially only planning on running a local codemod, but a new separate export (non-async SES shim) for Hermes makes sense 👍 like you will for XS

**Comment by leotm** [comment]
Updated description with deeper dive on `tameSymbolConstructor` with couple solutions ^ security considerations pending further thought

**Comment by leotm** [comment]
non-blocking improvements now tracked in
- https://github.com/endojs/endo/issues/2761

**Comment by leotm** [comment]
updated
- https://github.com/endojs/endo/issues/661
